author_id = "applejag"
app_id = "moonbit-test"
author_name = "Applejag"
app_name = "MoonBit test"

[files]
_bin = { path = "./target/wasm/release/build/superfly.wasm", copy = true }

# Fonts
"eg_6x12.fff" = { path = "assets/fonts/eg_6x12.fff" }

# Images
"smile-4.png" = { path = "assets/images/smile-4.png" }
"smile-2.png" = { path = "assets/images/smile-2.png" }
"smile-1.png" = { path = "assets/images/smile-1.png" }
