# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

version: 3

includes:
  example/input:
    taskfile: ./example/input
    dir: ./example/input
  example/shapes:
    taskfile: ./example/shapes
    dir: ./example/shapes
