# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

version: 3

includes:
  example/font: { taskfile: ./example/font, dir: ./example/font }
  example/image: { taskfile: ./example/image, dir: ./example/image }
  example/input: { taskfile: ./example/input, dir: ./example/input }
  example/shapes: { taskfile: ./example/shapes, dir: ./example/shapes }
  example/sudo: { taskfile: ./example/sudo, dir: ./example/sudo }

vars:
  MOON_MODULES:
    sh: echo ./src && find ./example -maxdepth 1 -mindepth 1 -type d

tasks:
  check:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: moon check -C {{.ITEM}}

  format:
    deps: [check]
    cmds:
      - for: { var: MOON_MODULES }
        cmd: moon fmt -C {{.ITEM}}

  test:
    cmds:
      - for: { var: MOON_MODULES }
        cmd: moon test -C {{.ITEM}}
