# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "applejag"
app_id = "moonbit-shapes"
author_name = "Applejag"
app_name = "MoonBit input test"

[files]
_bin = { path = "./target/wasm/release/build/shapes.wasm", copy = true }

# Fonts
"eg_6x12.fff" = { path = "../../assets/fonts/eg_6x12.fff" }
